os: osx
osx_image: xcode12u
language: cpp
compiler:
  - clang
  - gcc
addons:
  packages:
    - cmake
script: make
before_script:
 - brew install qt5
 - brew install openconnect
 - brew install make
 - brew link qt5 --force
 - git tag v1.5.4_preview
 - mkdir build-release
 - cd build-release
 - Qt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5 cmake -DCMAKE_BUILD_TYPE=Release ..

