os: osx
osx_image: xcode12u
compiler:
  - clang
  - gcc
addons:
  packages:
    - cmake
before_script:
 - brew install qt5
 - brew install openconnect
 - brew link qt5 --force
 - mkdir build-release
 - cd build-release
 - Qt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5 cmake -DCMAKE_BUILD_TYPE=Release ..ù - make

